use falco_plugin::extract::{ExtractFieldInfo, ExtractPlugin, field};

use crate::{EderaPlugin, EderaZoneSyscallContext};

impl ExtractPlugin for EderaPlugin {
    type ExtractContext = Option<EderaZoneSyscallContext>;
    type Event<'a> = falco_event::events::RawEvent<'a>;

    // See: https://falco.org/docs/reference/rules/supported-fields/#field-class-evt-for-system-calls
    const EXTRACT_FIELDS: &'static [ExtractFieldInfo<Self>] = &[
        field("edera.zone.id", &Self::extract_zone_id),
        field("evt.latency", &Self::extract_latency),
        field("evt.latency.s", &Self::extract_latency_s),
        field("evt.latency.ns", &Self::extract_latency_ns),
        field("evt.latency.human", &Self::extract_latency_human),
        field("evt.type", &Self::extract_type),
        field("evt.type.is", &Self::extract_type_is),
        field("syscall.type", &Self::extract_type), //alias
        field("evt.category", &Self::extract_category),
        field("evt.cpu", &Self::extract_cpu),
        field("evt.args", &Self::extract_args),
        field("evt.info", &Self::extract_args), //alias
        field("evt.arg", &Self::extract_arg),
        field("evt.dir", &Self::extract_dir),
        // TODO(bml) we can't support `evt.buffer` exactly like `libsinsp`
        // because the Falco plugin framework doesn't allow
        // returning raw bytebuffers at all. We can simulate the equivalent tho by
        // letting you provide a hex string and matching it, returning a bool.
        field("evt.buffer.contains", &Self::extract_buffer_contains_hex),
        field("evt.buflen", &Self::extract_buffer_len),
        // TODO(bml) we can't support `evt.rawres`, because the Falco plugin framework
        // only supports u64 so we can't represent negative retcodes (???)
        field("evt.res", &Self::extract_retval_str),
        field("evt.failed", &Self::extract_failed),
        field("evt.io_dir", &Self::extract_io_dir),
        field("evt.is_io", &Self::extract_is_io),
        field("evt.is_io_read", &Self::extract_is_io_read),
        field("evt.is_io_write", &Self::extract_is_io_write),
        field("evt.is_wait", &Self::extract_is_wait),
        field("evt.abspath", &Self::extract_abspath),
        field("evt.count", &Self::extract_count),
        field("evt.count.error", &Self::extract_count_error),
        field("evt.count.error.file", &Self::extract_count_error_file),
        field("evt.count.error.net", &Self::extract_count_error_net),
        field("evt.count.error.memory", &Self::extract_count_error_mem),
        field("evt.count.error.other", &Self::extract_count_error_other),
        field("evt.count.exit", &Self::extract_count_exit),
        field("evt.is_open_read", &Self::extract_is_open_read),
        field("evt.is_open_write", &Self::extract_is_open_write),
        field("evt.is_open_exec", &Self::extract_is_open_exec),
        field("evt.is_open_create", &Self::extract_is_open_create),
        field("proc.exe", &Self::extract_proc_exe),
        field("proc.pexe", &Self::extract_parent_proc_exe),
        field("proc.aexe", &Self::extract_nth_proc_exe),
        field("proc.exepath", &Self::extract_proc_exepath),
        field("proc.pexepath", &Self::extract_parent_proc_exepath),
        field("proc.aexepath", &Self::extract_nth_proc_exepath),
        field("proc.name", &Self::extract_proc_name),
        field("proc.pname", &Self::extract_parent_proc_name),
        field("proc.aname", &Self::extract_nth_proc_name),
        field("proc.args", &Self::extract_proc_args),
        field("proc.aargs", &Self::extract_nth_proc_args),
        field("proc.cmdline", &Self::extract_proc_cmdline),
        field("proc.pcmdline", &Self::extract_parent_proc_cmdline),
        field("proc.acmdline", &Self::extract_nth_proc_cmdline),
        field("proc.cmdnargs", &Self::extract_proc_argcount),
        field("proc.cmdlenargs", &Self::extract_proc_arglen),
        field("proc.exeline", &Self::extract_proc_exeline),
        field("proc.env", &Self::extract_proc_env),
        field("proc.aenv", &Self::extract_nth_proc_env),
        field("proc.cwd", &Self::extract_proc_cwd),
        field("proc.loginshellid", &Self::extract_proc_loginshellid),
        field("proc.tty", &Self::extract_proc_tty),
        field("proc.pid", &Self::extract_proc_pid),
        field("proc.ppid", &Self::extract_parent_proc_pid),
        field("proc.apid", &Self::extract_nth_proc_pid),
        field("proc.vpid", &Self::extract_proc_vpid),
        field("proc.pvpid", &Self::extract_parent_proc_vpid),
        field("proc.sid", &Self::extract_proc_sid),
        field("proc.sname", &Self::extract_proc_sname),
        field("proc.sid.exe", &Self::extract_proc_sexe),
        field("proc.sid.exepath", &Self::extract_proc_sexepath),
        field("proc.vpgid", &Self::extract_proc_vpgid),
        field("proc.vpgid.name", &Self::extract_proc_vpgidname),
        field("proc.vpgid.exe", &Self::extract_proc_vpgidexe),
        field("proc.vpgid.exepath", &Self::extract_proc_vpgidexepath),
        field("proc.pgid", &Self::extract_proc_pgid),
        field("proc.pgid.name", &Self::extract_proc_pgidname),
        field("proc.pgid.exe", &Self::extract_proc_pgidexe),
        field("proc.pgid.exepath", &Self::extract_proc_pgidexepath),
        field("proc.duration", &Self::extract_proc_duration),
        field("proc.ppid.duration", &Self::extract_parent_proc_duration),
        field("proc.pid.ts", &Self::extract_proc_pid_ts),
        field("proc.ppid.ts", &Self::extract_parent_proc_pid_ts),
        field("proc.is_exe_writable", &Self::extract_proc_exe_writable),
        field(
            "proc.is_exe_upper_layer",
            &Self::extract_proc_exe_upper_layer,
        ),
        field(
            "proc.is_exe_lower_layer",
            &Self::extract_proc_exe_lower_layer,
        ),
        field("proc.is_exe_from_memfd", &Self::extract_proc_exe_from_memfd),
        field("proc.is_sid_leader", &Self::extract_proc_sid_leader),
        field("proc.is_vpgid_leader", &Self::extract_proc_vpgid_leader),
        field("proc.is_pgid_leader", &Self::extract_proc_pgid_leader),
        field("proc.exe_ino", &Self::extract_proc_exe_ino),
        field("proc.exe_ino_ctime", &Self::extract_proc_exe_ino_ctime),
        field("proc.exe_ino_mtime", &Self::extract_proc_exe_ino_mtime),
        field(
            "proc.exe_ino_ctime_duration_proc_start",
            &Self::extract_proc_exe_ino_ctime_duration_proc_start,
        ),
        field(
            "proc.exe_ino_ctime_duration_pidns_start",
            &Self::extract_proc_exe_ino_ctime_duration_pidns_start,
        ),
        field("thread.cap_permitted", &Self::extract_thread_cap_permitted),
        field(
            "thread.cap_inheritable",
            &Self::extract_thread_cap_inheritable,
        ),
        field("thread.cap_effective", &Self::extract_thread_cap_effective),
        field("proc.fdopencount", &Self::extract_proc_fdopencount),
        field("proc.fdlimit", &Self::extract_proc_fdlimit),
        field("proc.fdusage", &Self::extract_proc_fdusage),
        field("proc.vmsize", &Self::extract_proc_vmsize),
        field("proc.vmrss", &Self::extract_proc_vmrss),
        field("proc.vmswap", &Self::extract_proc_vmswap),
        field("thread.pfmajor", &Self::extract_thread_pfmajor),
        field("thread.pfminor", &Self::extract_thread_pfminor),
        field("thread.tid", &Self::extract_thread_tid),
        field("thread.ismain", &Self::extract_thread_ismain),
        field("thread.vtid", &Self::extract_thread_vtid),
        field("thread.exectime", &Self::extract_thread_exectime),
        field("thread.totexectime", &Self::extract_thread_total_exectime),
        field("thread.cgroups", &Self::extract_thread_cgroups),
        field("thread.cgroup", &Self::extract_thread_cgroup),
        field("proc.nthreads", &Self::extract_proc_nthreads),
        field("proc.nchilds", &Self::extract_proc_nchilds),
        field("thread.vmsize", &Self::extract_thread_vmsize),
        field("thread.vmrss", &Self::extract_thread_vmrss),
        field("proc.stdin.type", &Self::extract_proc_stdin_type),
        field("proc.stdout.type", &Self::extract_proc_stdout_type),
        field("proc.stderr.type", &Self::extract_proc_stderr_type),
        field("proc.stdin.name", &Self::extract_proc_stdin_name),
        field("proc.stdout.name", &Self::extract_proc_stdout_name),
        field("proc.stderr.name", &Self::extract_proc_stderr_name),
        // TODO BML cannot support these ATM, as in libsinsp
        // they are populated by synthesized events generated by manually polling `/proc/<pid>/stat`
        // every 1s.
        // field("thread.cpu", ),
        // field("thread.cpu.user", ),
        // field("thread.cpu.system", ),
        // TODO BML cannot support these ATM, as in libsinsp
        // they are populated by synthesized events generated by manually polling `/proc`
        // every 1s.
        // field("user.uid", ),
        // field("user.name", ),
        // field("user.homedir", ),
        // field("user.shell", ),
        // field("user.loginuid", ),
        // field("user.loginname", ),
        // field("group.gid", ),
        // field("group.name", ),
        field("fd.num", &Self::extract_fd_num),
        field("fd.type", &Self::extract_fd_type),
        field("fd.typechar", &Self::extract_fd_typechar),
        field("fd.name", &Self::extract_fd_name),
        field("fd.directory", &Self::extract_fd_dir),
        field("fd.filename", &Self::extract_fd_filename),
        field("fd.ip", &Self::extract_fd_ip),
        field("fd.cip", &Self::extract_fd_cip),
        field("fd.sip", &Self::extract_fd_sip),
        field("fd.lip", &Self::extract_fd_lip),
        field("fd.rip", &Self::extract_fd_rip),
        field("fd.port", &Self::extract_fd_port),
        field("fd.cport", &Self::extract_fd_cport),
        field("fd.sport", &Self::extract_fd_sport),
        field("fd.lport", &Self::extract_fd_lport),
        field("fd.rport", &Self::extract_fd_rport),
        field("fd.l4proto", &Self::extract_fd_l4proto),
        field("fd.sockfamily", &Self::extract_fd_sockfamily),
        field("fd.is_server", &Self::extract_fd_is_server),
        field("fd.uid", &Self::extract_fd_uid),
        // TODO(bml) like other container fields,
        // these need the existing Falco OSS container plugin to be updated to be Edera-aware.
        // field("fd.containername", &Self::extract_fd_uid),
        // field("fd.containerdirectory", &Self::extract_fd_uid),
        field("fd.proto", &Self::extract_fd_proto),
        field("fd.cproto", &Self::extract_fd_cproto),
        field("fd.sproto", &Self::extract_fd_sproto),
        field("fd.lproto", &Self::extract_fd_lproto),
        field("fd.rproto", &Self::extract_fd_rproto),
        field("fd.net", &Self::extract_fd_net),
        field("fd.cnet", &Self::extract_fd_cnet),
        field("fd.snet", &Self::extract_fd_snet),
        field("fd.lnet", &Self::extract_fd_lnet),
        field("fd.rnet", &Self::extract_fd_rnet),
        field("fd.connected", &Self::extract_fd_connected),
        // TODO(bml) this requires adding state tracking to the event
        // to determine if *our parsing* rewrote the FD's tuple.
        // Skipping this for now/this seems low-value.
        // field("fd.name_changed", &Self::extract_fd_connected),
        field("fd.cip.name", &Self::extract_fd_cip_name),
        field("fd.sip.name", &Self::extract_fd_sip_name),
        field("fd.lip.name", &Self::extract_fd_lip_name),
        field("fd.rip.name", &Self::extract_fd_rip_name),
        field("fd.dev", &Self::extract_fd_dev),
        field("fd.dev.major", &Self::extract_fd_dev_major),
        field("fd.dev.minor", &Self::extract_fd_dev_minor),
        field("fd.ino", &Self::extract_fd_ino),
        field("fd.nameraw", &Self::extract_fd_nameraw),
        field("fd.types", &Self::extract_fd_types),
        field("fd.is_upper_layer", &Self::extract_fd_upper_layer),
        field("fd.is_lower_layer", &Self::extract_fd_lower_layer),
        field("fs.path.name", &Self::extract_fs_path_name),
        field("fs.path.nameraw", &Self::extract_fs_path_nameraw),
        field("fs.path.source", &Self::extract_fs_path_source),
        field("fs.path.sourceraw", &Self::extract_fs_path_sourceraw),
        field("fs.path.target", &Self::extract_fs_path_target),
        field("fs.path.targetraw", &Self::extract_fs_path_targetraw),
        field("fdlist.nums", &Self::extract_fdlist_nums),
        field("fdlist.names", &Self::extract_fdlist_names),
        field("fdlist.cips", &Self::extract_fdlist_cips),
        field("fdlist.sips", &Self::extract_fdlist_sips),
        field("fdlist.cports", &Self::extract_fdlist_cports),
        field("fdlist.sports", &Self::extract_fdlist_sports),
    ];
}
